apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: devops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: devops-api
          image: ghcr.io/paulxavy/devops:latest
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
            - name: API_KEY
              value: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: YmVzdF9qd3Rfc2VjcmV0Cg==
